-- Fase 17: historial persistente de salud de Inventario.
-- Esta migración NO se ejecuta automáticamente desde la aplicación.

create table if not exists inventory_health_snapshots (
    id bigint generated by default as identity primary key,
    recorded_at timestamptz not null default now(),
    recorded_by text not null,
    health_score integer not null check (health_score between 0 and 100),
    completion_percent numeric(5,2) not null check (completion_percent between 0 and 100),
    total_items integer not null check (total_items >= 0),
    critical_findings integer not null check (critical_findings >= 0),
    high_findings integer not null check (high_findings >= 0),
    medium_findings integer not null check (medium_findings >= 0),
    general_status text not null,
    source_version text not null default 'inventory-health-v1',
    notes text,
    created_at timestamptz not null default now()
);

create index if not exists idx_inventory_health_snapshots_recorded_at
    on inventory_health_snapshots (recorded_at desc);

comment on table inventory_health_snapshots is
    'Observaciones auditables del índice orientativo de salud de Inventario. No constituye valoración contable.';
